import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <link
          href="https://fonts.googleapis.com/css2?family=Kumar+One&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Jomhuria:wght@400"
        />

        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Kumar+One:wght@400"
        />

        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Abhaya+Libre:wght@400;700"
        />
        {children}
      </body>
    </html>
  );
}
